<?php

declare(strict_types=1);

namespace App\Tests\Module\Product;

use App\Module\Product\Feature;
use App\Module\Product\Product;
use PHPUnit\Framework\TestCase;
use Ramsey\Uuid\UuidInterface;

class FeatureTest extends TestCase
{
    public function testConstructorAndGetId(): void
    {
        $value = 'Test Feature';
        $feature = new Feature($value);
        
        $this->assertInstanceOf(UuidInterface::class, $feature->getId());
        $this->assertEquals($value, $feature->getValue());
        $this->assertIsArray($feature->getProducts());
        $this->assertEmpty($feature->getProducts());
    }

    public function testGetSlug(): void
    {
        $value = 'Test Feature';
        $feature = new Feature($value);
        
        // We need to set the slug property using reflection since it's generated by Gedmo
        $reflectionProperty = new \ReflectionProperty(Feature::class, 'slug');
        $reflectionProperty->setAccessible(true);
        $reflectionProperty->setValue($feature, 'test-feature');
        
        $this->assertEquals('test-feature', $feature->getSlug());
    }

    public function testGetProductsWithInjectedProducts(): void
    {
        $feature = new Feature('Test Feature');
        
        // Use reflection to access and modify the products collection
        $reflectionProperty = new \ReflectionProperty(Feature::class, 'products');
        $reflectionProperty->setAccessible(true);
        $productsCollection = $reflectionProperty->getValue($feature);
        
        // Create mock Product objects
        $product1 = $this->createMock(Product::class);
        $product2 = $this->createMock(Product::class);
        $product3 = $this->createMock(Product::class);
        
        // Add products to the collection
        $productsCollection->add($product1);
        $productsCollection->add($product2);
        $productsCollection->add($product3);
        
        $products = $feature->getProducts();
        
        $this->assertIsArray($products);
        $this->assertCount(3, $products);
        $this->assertSame($product1, $products[0]);
        $this->assertSame($product2, $products[1]);
        $this->assertSame($product3, $products[2]);
    }


    public function testGetSlugWithUninitializedSlug(): void
    {
        $value = 'Test Feature';
        $feature = new Feature($value);
        
        // Without setting slug via reflection, it remains uninitialized
        // Due to strict types and return type string, this will throw TypeError
        $this->expectException(\TypeError::class);
        $feature->getSlug();
    }


    public function testUuidUniquenessAcrossMultipleInstances(): void
    {
        $value = 'Duplicate Feature';
        $uuids = [];
        
        for ($i = 0; $i < 100; $i++) {
            $feature = new Feature($value);
            $uuid = $feature->getId()->toString();
            $this->assertNotContains($uuid, $uuids, 'UUID collision detected');
            $uuids[] = $uuid;
        }
        
        $this->assertCount(100, $uuids);
        $this->assertCount(100, array_unique($uuids));
    }


    public function testConstructorWithSpecialCharactersAndUnicode(): void
    {
        $value = 'Test™ Féature 日本語 @#$%^&*()';
        $feature = new Feature($value);
        
        $this->assertInstanceOf(UuidInterface::class, $feature->getId());
        $this->assertEquals($value, $feature->getValue());
        $this->assertSame('Test™ Féature 日本語 @#$%^&*()', $feature->getValue());
    }


    public function testConstructorWithVeryLongStringValue(): void
    {
        $value = str_repeat('A', 1500);
        $feature = new Feature($value);
        
        $this->assertInstanceOf(UuidInterface::class, $feature->getId());
        $this->assertEquals($value, $feature->getValue());
        $this->assertEquals(1500, strlen($feature->getValue()));
        $this->assertIsArray($feature->getProducts());
        $this->assertEmpty($feature->getProducts());
    }


    public function testConstructorWithEmptyStringValue(): void
    {
        $value = '';
        $feature = new Feature($value);
        
        $this->assertInstanceOf(UuidInterface::class, $feature->getId());
        $this->assertEquals('', $feature->getValue());
        $this->assertIsArray($feature->getProducts());
        $this->assertEmpty($feature->getProducts());
    }



}
