<?php

declare(strict_types=1);

namespace App\Tests\Module\Product;

use App\Module\Product\Feature;
use App\Module\Product\Product;
use PHPUnit\Framework\TestCase;
use Ramsey\Uuid\UuidInterface;

class FeatureTest extends TestCase
{
    public function testConstructorAndGetId(): void
    {
        $value = 'Test Feature';
        $feature = new Feature($value);
        
        $this->assertInstanceOf(UuidInterface::class, $feature->getId());
        $this->assertEquals($value, $feature->getValue());
        $this->assertIsArray($feature->getProducts());
        $this->assertEmpty($feature->getProducts());
    }

    public function testGetSlug(): void
    {
        $value = 'Test Feature';
        $feature = new Feature($value);
        
        // We need to set the slug property using reflection since it's generated by Gedmo
        $reflectionProperty = new \ReflectionProperty(Feature::class, 'slug');
        $reflectionProperty->setAccessible(true);
        $reflectionProperty->setValue($feature, 'test-feature');
        
        $this->assertEquals('test-feature', $feature->getSlug());
    }


}
